name: jsii_runtime
description: The Dart runtime of the jsii engine.
version: 0.1.0
homepage: https://aws.github.io/jsii/
repository: https://github.com/aws/jsii
issue_tracker: https://github.com/aws/jsii/issues

environment:
  sdk: "^3.0.0"

dependencies:
  amplify_core: ">=1.2.0 <1.3.0"
  async: ^2.11.0
  aws_common: ">=0.5.0 <0.6.0"
  collection: ^1.17.2
  file: ^7.0.0
  json_annotation: ^4.8.1
  meta: ^1.9.1
  path: ^1.8.3
  stack_trace: ^1.11.1
  tar: ^0.5.6

dev_dependencies:
  amplify_lints: ^2.0.0
  build_runner: ^2.0.0
  build_version: ^2.1.1
  json_serializable: ^6.7.1
  test: ^1.16.0
